services:
  postgres:
    container_name: postgresql-for-vcs-integration
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-volume:/var/lib/postgresql
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
